<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A home page for the company, containing all neccesary details.">
    <meta name="keywords" content="title, description, skills, email, phone, number, company, name">
    <meta name="author" content="Sophie Kroezen & Akhila Sripriyadarshini Gollamudi">
    <title>Home Page</title>
    <link rel="stylesheet" href="styles/styles.css"> <!-- Link to the CSS file for styling -->
    <link rel="websiteicon" href="images/sa_coders_logo.png" type="image/png"> <!-- Link to the favicon for the website -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&display=swap" rel="stylesheet">
</head>   
    <footer>
        <a href="https://sophieella06.atlassian.net/jira/software/projects/SCPP1/boards/34/backlog">Jira Project</a>
        <a href="https://github.com/105924231/projectpart1/tree/main">GitHub Page</a>
        <a href="mailto:105924231@student.swin.edu.au">Email Sophie</a>
        <a href="mailto:105931972@student.swin.edu.au">Email Akhila</a>
    </footer>
</html>