<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A home page for the company, containing all neccesary details.">
    <meta name="keywords" content="title, description, skills, email, phone, number, company, name">
    <meta name="author" content="Sophie Kroezen & Akhila Sripriyadarshini Gollamudi">
    <title>Home Page</title>
    <link rel="stylesheet" href="styles/styles.css"> <!-- Link to the CSS file for styling -->
    <link rel="websiteicon" href="images/sa_coders_logo.png" type="image/png"> <!-- Link to the favicon for the website -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&display=swap" rel="stylesheet">
</head>

<body class="index-body">
    <header class="header-container">
        <!-- Logo and Title Section. Logo is sourced from GenAI: create a simple logo with the words "S.A Coders" in relation to HTML.-->
        <a href="index.html"><img src="images/sa_coders_logo.png" alt="S.A Coders Logo" class="logo" width="120" height="75"></a>

       
        <!--Nav bar-->

        <div class="main-menu">
            <main>   <!-- Unordered List for the different pages in this project. They will open in a different tab.-->
                <nav>
                    <a href="index.html" target="_self" title="Home">Home</a>
                    <a href="jobs.html" target="_self" title="Jobs">Jobs</a>
                    <a href="about.html" target="_self" title="About">About Us</a>
                    <a href="#start" target="_self" title="Apply">Apply</a>
                </nav>
            </main>
        </div>
    </header>