<!DOCTYPE html>
<html lang="en">
    <header>
        <p><a href="index.html" target="_blank"><img src= "images/sa_coders_logo.png" alt="S.A Coders Logo" class="logo" width="120" height="75"></a></p>
        <nav class="about-nav">
            <li class="menu"><a href="index.html">Home</a></li>
            <li class="menu"><a href="jobs.html">Jobs</a></li>
            <li class="menu"><a href="#aboutus">About Us</a></li>
            <li class="menu"><a href="apply.html">Apply</a></li>
        </nav>
    </header>