<!DOCTYPE html>
<html lang="en">
    <header>
        <p><a href="index.html" target="_blank"><img src= "images/sa_coders_logo.png" alt="S.A Coders Logo" class="logo" width="120" height="75"></a></p>
        <nav class="about-nav">
            <li class="menu"><a href="index.php">Home</a></li>
            <li class="menu"><a href="jobs.php">Jobs</a></li>
            <li class="menu"><a href="#about.php">About Us</a></li>
            <li class="menu"><a href="apply.php">Apply</a></li>
        </nav>
    </header>